"""log_table

Revision ID: 36de46770c92
Revises: c4f34a197da4
Create Date: 2019-12-10 19:42:33.123132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36de46770c92'
down_revision = 'c4f34a197da4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('created_timestamp', sa.DateTime(), nullable=True),
    sa.Column('updated_timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_entry_created_timestamp'), 'log_entry', ['created_timestamp'], unique=False)
    op.create_index(op.f('ix_log_entry_updated_timestamp'), 'log_entry', ['updated_timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_log_entry_updated_timestamp'), table_name='log_entry')
    op.drop_index(op.f('ix_log_entry_created_timestamp'), table_name='log_entry')
    op.drop_table('log_entry')
    # ### end Alembic commands ###
