"""actually changed log entries to posts

Revision ID: 3f0fb80d30af
Revises: 36de46770c92
Create Date: 2019-12-14 14:11:59.099563

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3f0fb80d30af'
down_revision = '36de46770c92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('created_timestamp', sa.DateTime(), nullable=True),
    sa.Column('updated_timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_created_timestamp'), 'post', ['created_timestamp'], unique=False)
    op.create_index(op.f('ix_post_updated_timestamp'), 'post', ['updated_timestamp'], unique=False)
    op.drop_index('ix_log_entry_created_timestamp', table_name='log_entry')
    op.drop_index('ix_log_entry_updated_timestamp', table_name='log_entry')
    op.drop_table('log_entry')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_entry',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('success', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('body', sa.VARCHAR(length=140), autoincrement=False, nullable=True),
    sa.Column('created_timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='log_entry_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='log_entry_pkey')
    )
    op.create_index('ix_log_entry_updated_timestamp', 'log_entry', ['updated_timestamp'], unique=False)
    op.create_index('ix_log_entry_created_timestamp', 'log_entry', ['created_timestamp'], unique=False)
    op.drop_index(op.f('ix_post_updated_timestamp'), table_name='post')
    op.drop_index(op.f('ix_post_created_timestamp'), table_name='post')
    op.drop_table('post')
    # ### end Alembic commands ###
